name: CI
on: [push]

env:
  OPENTAP_ANSI_COLORS: true
  OPENTAP_NO_UPDATE_CHECK: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_CONSOLE_ANSI_COLOR: true
  
jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/heads/release') || contains(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '6.0.x'
      - name: Build
        run: dotnet publish -c Release
      - name: Copy TapPackage
        run: cp OpenTAP.TUI/bin/Release/TUI*.TapPackage .
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          retention-days: 5
          path: "TUI*.TapPackage"
  
  Publish:
    runs-on: ubuntu-latest
    needs: Build
    #if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/heads/release') || contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: StefanHolst/setup-opentap@v1.0
        with:
          version: 9.17.0
          package: "PackagePublish"
      - name: Install PackagePublish
        run: tap package install PackagePublish --version rc
      - name: Publish
        run: tap package publish "TUI*.TapPackage"